Message match
BlueBubblesApp/bluebubbles-server pull request #301
Opened 2022-02-08 18:28 UTC by mrsylerpowers

2022-02-08 18:32 UTC, zlshames requested changes

2022-02-08 18:32 UTC, zlshames commented on packages/server/src/server/api/v1/apple/actions.ts
> +            messageAwaiter = new MessagePromise({chatGuid: chatGuid, text:message, isAttachment: false, sentAt:now,  tempGuid:tempGuid});
please add a space after all colons here

2022-02-08 18:32 UTC, zlshames commented on packages/server/src/server/api/v1/interfaces/messageInterface.ts
> +        const awaiter = new MessagePromise({chatGuid: chatGuid, text:message, isAttachment:false, sentAt:now, subject:subject, tempGuid:tempGuid});
spaces

2022-02-08 18:32 UTC, zlshames commented on packages/server/src/server/api/v1/apple/actions.ts
> +            attachmentAwaiter = new MessagePromise({chatGuid: chatGuid,text: `->${aName}`, isAttachment:true, sentAt:now, tempGuid:attachmentGuid});
spaces

2022-02-08 18:32 UTC, zlshames commented on packages/server/src/server/api/v1/interfaces/messageInterface.ts
> +        const awaiter = new MessagePromise({chatGuid,text: `->${aName}`, isAttachment:true, sentAt:now, tempGuid:attachmentGuid});
spaces

2022-02-08 18:32 UTC, zlshames commented on packages/server/src/server/api/v1/interfaces/messageInterface.ts
> +        const awaiter = new MessagePromise({chatGuid: chatGuid, text:messageText, isAttachment:false, sentAt:now, tempGuid:tempGuid});
spaces

2022-02-08 18:32 UTC, zlshames commented on packages/server/src/server/managers/outgoingMessageManager/messagePromise.ts
> +    sentAt: Date | number;
Can this be a number or date? Do we pass it as both? Do we even handle if it's one or the other or just one case?

2022-02-08 18:37 UTC, mrsylerpowers commented on packages/server/src/server/managers/outgoingMessageManager/messagePromise.ts
> +    sentAt: Date | number;
L51 is where this is done

2022-02-08 18:46 UTC, mrsylerpowers commented on packages/server/src/server/managers/outgoingMessageManager/messagePromise.ts
> +    sentAt: Date | number;
Always passed as a number I think

2022-02-08 19:38 UTC, zlshames commented on packages/server/src/server/managers/outgoingMessageManager/messagePromise.ts
> +    sentAt: Date | number;
If it's always a number, and we don’t manually handle dates, can we just make the type be a number?

2022-02-08 20:29 UTC, merged

2022-02-09 05:02 UTC, mrsylerpowers commented on packages/server/src/server/managers/outgoingMessageManager/messagePromise.ts
> +    sentAt: Date | number;
Yes. I definitely think that is a better solution