V2 API with Tokens!
BlueBubblesApp/bluebubbles-server pull request #592
Opened 2023-11-21 05:34 UTC by juliettebee

Hiya! So I noticed BlueBubbles doesn't use tokens and has the interesting design choice of using url params instead of headers so I created a version 2 of the API with user created tokens! **This is very much a proof of concept, it has not been thoroughly tested, it was hacked together in 4 hours**. This is the first time I've written in Typescript so lemme know if something's wrong! 

## Changes:
* Token panel in settings
* V2 API requiring a `Token` header with the value of `[token name] [token password]`
* Two new API routes
     - `token/register` POST `{"name": "token name", "password": "token password"}`
     - `token/delete` POST `{"name": "token name"}`

2023-11-21 23:17 UTC, juliettebee commented
Added route: `token/refresh` POST `{"name": "token name", "password": "token password", expireAt: 0}`
Where expireAt is how much longer to add to the expiration in Unix time:)

2024-03-09 14:51 UTC, zlshames commented
Sorry I havent looked into this yet. I'm waiting for the right time to properly implement it

2024-03-09 15:01 UTC, zlshames requested changes
Thanks for submitting this of course! I have some changes that I think would be good to make. It may complicate some of the logic in some cases, but using JWTs and being able to refresh a token is typical in many Bearer auth flows

2024-03-09 15:01 UTC, zlshames commented on packages/server/src/server/api/http/api/v2/middleware/authMiddleware.ts
> +    const tokenID = tokenParts[0]
Can you explain what the token ID is supposed to be? Typically the flow is the following:

1. User authenticates using password
2. Server generates an `access_token` and `refresh_token` and returns it to the client
    - Access token may be a JWT to validate authenticity and make sure it's not been tampered with
4. Client can then authenticate using the following header `Authorization: Bearer {access_token}`
5. Client can use the refresh token when the access token is expired

2024-03-09 15:01 UTC, zlshames commented on packages/server/src/server/databases/server/entity/Token.ts
> +    password: string;
Ultimately, instead of `password` here, I think we'd want `accessToken` and `refreshToken`. We also probably don't need a name. Unless we want the name to correspond to the "device ID", which we'd put in the encoded JWT

2024-03-09 15:01 UTC, zlshames commented on packages/server/src/server/services/ipcService/index.ts
> +        ipcMain.handle("create-token", async(event, args) => {
We probably don't need to create or update tokens from the UI, since the flow will exclusively be handled by clients. I do like the idea of being able to view what tokens have been distributed and can remove/unauthorize clients as-needed

2024-03-09 15:01 UTC, zlshames commented on packages/ui/src/app/components/modals/AddTokenDialog.tsx
Again, probably don't need to be able to create tokens from the UI. These tokens won't be static as they can change and be updated based on if they are refreshed and what not.

2024-03-09 15:01 UTC, zlshames commented on packages/ui/src/app/constants.ts
Definitely a cool idea to add an event for when new tokens are registered for monitoring purposes. Good idea.

2024-05-07 17:59 UTC, closed without merging